name: 7fjell
favicon: null
layout_spectrum: 0.26504
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#929398'
    - '#231F20'
    - '#007AFF'
    - '#7EC9DF'
  brandStrength: 1
  lightness: 0.08510314
  saturation: 0.5
  rhythmicContrast: 0.3906766
purpose: []
